### ISSUE TITLE
Implement tracking of courses taken by User (arranged by term)

### ISSUE THREAD

**Issue by timweri** [timweri/uwcourse-api#9]
Feature allows users to mark a course as taken for a specific term. In the User model, these taken courses will be grouped by term.

It will look something like:
```
taken_courses: {
    "<term-id>": [<course-id>, <course-id>, ...],
    "<term-id>": [<course-id>, <course-id>, ...],
    ....
}
```

Need to decide if this should be a nested subdocument within User model or document in a separate TakenCourse model. For now, its placeholder is incorrectly defined in User model as the `terms` field.

- [ ] Add taken course
- [ ] Remove taken course
- [ ] Collision check between terms (do not allow one user to take one course multiple times)
- [ ] Collision check between crosslistings and antirequisites like advanced versions. (Low priority)
